# Generated by Django 5.0.1 on 2024-01-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.ManyToManyField(to='posts.quantity'),
        ),
    ]
