# Generated by Django 5.0.1 on 2024-01-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_preparationstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='post',
            name='preparationStep',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AddField(
            model_name='preparationstep',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.quantity'),
        ),
    ]
