# Generated by Django 5.0.1 on 2024-01-17 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_ingredient_quantity_remove_ingredient_recipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient_quantity',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.ingredient'),
        ),
    ]
