# Generated by Django 5.0.1 on 2024-01-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_ingredient_quantity_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_quantity',
            old_name='recipe',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='preparationstep',
            old_name='recipe',
            new_name='post',
        ),
    ]
