# Generated by Django 5.0.1 on 2024-02-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_recipe_ingredient_quantity_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='recipeName',
            new_name='recipe_name',
        ),
        migrations.AddField(
            model_name='post',
            name='date_of_publication',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ingredient_quantity',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
    ]
