# Generated by Django 5.0.1 on 2024-02-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_post_chef_alter_preparationstep_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='chef',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='quantityMeasure',
            new_name='quantity_measure',
        ),
        migrations.RenameField(
            model_name='quantity',
            old_name='quantityNumber',
            new_name='quantity_number',
        ),
        migrations.RemoveField(
            model_name='ingredient_quantity',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_of_publication',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='recipe_name',
        ),
        migrations.RemoveField(
            model_name='preparationstep',
            name='post',
        ),
        migrations.AddField(
            model_name='preparationstep',
            name='step_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecipePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes_count', models.IntegerField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('recipe_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.recipepost')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient_quantity',
            name='recipe_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.recipepost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preparationstep',
            name='recipe_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.recipepost'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecipeRepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('recipe_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.recipepost')),
            ],
        ),
    ]
