# Generated by Django 5.0.1 on 2024-02-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_chef_post_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecomment',
            name='likes_count',
        ),
    ]
