# Generated by Django 5.0.1 on 2024-03-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_repost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
